/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yang_myapplication_JNIUitl */

#ifndef _Included_com_example_yang_myapplication_JNIUitl
#define _Included_com_example_yang_myapplication_JNIUitl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yang_myapplication_JNIUitl
 * Method:    text
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yang_myapplication_JNIUitl_text
  (JNIEnv *env, jobject){
  return env -> NewStringUTF("Hello World!");
  };

#ifdef __cplusplus
}
#endif
#endif
